// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	domain "go-poc-example/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MemDB is an autogenerated mock type for the CouponRepository type
type MemDB struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *MemDB) FindAll() ([]domain.Coupon, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Coupon, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Coupon); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Coupon)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByCode provides a mock function with given fields: code
func (_m *MemDB) FindByCode(code string) (*domain.Coupon, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *domain.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Coupon, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Coupon); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Coupon)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ID
func (_m *MemDB) FindByID(ID string) (*domain.Coupon, error) {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Coupon, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Coupon); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Coupon)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: coupon
func (_m *MemDB) Save(coupon domain.Coupon) error {
	ret := _m.Called(coupon)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Coupon) error); ok {
		r0 = rf(coupon)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMemDB creates a new instance of MemDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemDB {
	mock := &MemDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
